### ISSUE TITLE
Unable to populate the table! 

### ISSUE THREAD

**Issue by shreehari-verna** [TheInformationLab/Tableau-ExtractAPI-App#3]
./extract --schema /Users/shreehari/Downloads/sample.json --output hello.hyper --localread --overwrite
[INFO] Importing schema file /Users/shreehari/Downloads/sample.json
[INFO] Schema Imported
[INFO] Overwriteing existing hello.hyper file
[INFO] Creating new local Hyper instance
[INFO] Instance created. Building connection to hello.hyper
[INFO] Connection established. Adding table to Hyper database
[INFO] The databse is ready to go. Let's get it populated
[INFO] Importing:   0%|                                   | 0/1 [00:00<?, ?it/s][INFO] SQLCMD: COPY test FROM '/Users/shreehari/Downloads/test.csv' WITH (FORMAT CSV);
HYPER:11: extra data after last expected column file:'/Users/shreehari/Downloads/test.csv' line:1
  Severity: ErrorSeverity.ERROR
[ERROR] A fatal error occurred while populating the extract:
 None 
Exiting now.

Traceback (most recent call last):
  File "extract.py", line 201, in populateExtract
  File "site-packages/tableauhyperapi/connection.py", line 255, in execute_command
  File "site-packages/tableauhyperapi/impl/dllutil.py", line 118, in check
tableauhyperapi.hyperexception.HyperException: HYPER:11: extra data after last expected column file:'/Users/shreehari/Downloads/test.csv' line:1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract.py", line 259, in <module>
  File "extract.py", line 252, in main
  File "extract.py", line 206, in populateExtract
NameError: name 'exit' is not defined
[11303] Failed to execute script extract

**Comment by shreehari-verna** [comment]
I was able to solve this by running the chmod +x on the extract file again
